### PR TITLE
Updating amadeus address

### PR DESCRIPTION
**Pull request by fabiocesso**
Including Mainnet address

### CODE REVIEW

**Comment by fabiocesso** [comment]
We add the Mainnet Amadeus address and change the Kovan address.

**Comment by fabiocesso** [comment]
Hello Tom,

The Amadeus Relayer will not behave like a decentralized exchage. Our idea
is to be used by dApps, implementing the Reserve Manager strategy. We don't
consider that the endpoint "/ordebook" will be used in our usage scenarios.
Is that mandatory to the registry?

Regarding Mainnet, we are in the final testing phase and we will announce
the launch on Mainnet in a few weeks.

**Comment by tomhschmidt** [comment]
Ah right! I forgot -- makes sense. Merged :)

**Comment by fabiocesso** [comment]
Thanks!

**Pull request merged**
