### PR TITLE
added metamorph relayer

### PR DESCRIPTION
**Pull request by tommycp3**
We are doing this so we can become official partners of 0x protocol.

### CODE REVIEW

**Comment by tommycp3** [comment]
Do you know why it failed?

**Comment by tomhschmidt** [comment]
Not sure what's up with that, because it definitely merged and you're now added

**Comment by tommycp3** [comment]
That is great news we are now officially added.

We provided a logo: https://github.com/0xProject/0x-relayer-registry/blob/master/images/logos/metamorph.png

To celebrate our collective collaboration could we please put this logo:

Here: https://0x.org
and here: https://0x.org/portal

I noticed other logos are not white but the ones on the website are complete white. 

I can provide a completely white logo if you need it.

**Comment by danlewcom** [comment]
Hi @tomhschmidt just following up regarding having our last comment, thanks.

**Pull request merged**
